version: 1.0
jobs:

    kaggle_download_train:
        module: durian/module/kaggle_download
        input: {}
        output: 
            download_file: train.csv.zip
        parameters:
            competition: jigsaw-toxic-comment-classification-challenge
            file: train.csv.zip

    kaggle_download_test:
        module: durian/module/kaggle_download
        input: {}
        output: 
            download_file: test.csv.zip
        parameters:
            competition: jigsaw-toxic-comment-classification-challenge
            file: test.csv.zip
